<?php 
    $skin = '';
    
    if (!empty($settings['quantitySpinnerSkin'])) {
        $skin = $settings['quantitySpinnerSkin'];
    }
?>
<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('#festi-cart-pop-up-content').bPopup({
            modalClose: true,
            positionStyle: 'fixed',
            onClose: function() {
                jQuery('div.festi-cart-pop-up-content').removeClass('festi-cart-pop-up-content-active');
            }
        }, function () {
            showQuantitySpinnerSkin('<?php echo $skin;?>');
        });
        jQuery('div.festi-cart-pop-up-content').addClass('festi-cart-pop-up-content-active');
    })
</script>
