<div class="festi-cart-pop-up-products-content">
    <div class="festi-cart-error-message"></div>
    <div id="festi-cart-pop-up-products-list-body">
        <table class="festi-cart-list">
            <?php
            $productsCount = $woocommerce->getCartContentsCount();

            if ($productsCount > 0) {

                $changeBgColor = 'festi-cart-next';
                $maxStep = 5;
                $step = 0;
                
                foreach ($woocommerce->getCartContents() as $cart_item_key => $cart_item) {
                    
                    $isHide = apply_filters(WOOCARTPRO_FILTER_POPUP_HIDE_ITEM_PRODUCT, false, $cart_item);
                    if ($isHide) {
                        continue;
                    }
                    
                    $step++;

                    $removeAttributes = ' data-id="'.$cart_item['product_id'].'"';

                    $changeBgColor = ($changeBgColor != 'festi-cart-next') ? 'festi-cart-next' : '';

                    $product = $cart_item['data'];
                    $productImg = '';
                    if (array_key_exists('displayProductsPictures', $settings) && !empty($settings['displayProductsPictures'])) {

                        if (array_key_exists('productDefaultThumbnail', $settings) && !empty($settings['productDefaultThumbnail'])) {
                            $img = $product->get_image();
                        } else {
                            if ($settings['productImageMaxHeight'] == 0) {
                                $settings['productImageMaxHeight'] = $settings['productImageMaxWidth'];
                            }

                            if ($settings['productImageMaxWidth'] == 0) {
                                $settings['productImageMaxWidth'] = $settings['productImageMaxHeight'];
                            }

                            $productId = ($cart_item['variation_id']) ? $woocommerce->getID($product) : $woocommerce->getParentID($product);

                            $variationId = ($cart_item['variation_id']) ? $cart_item['variation_id'] : '';

                            if (!has_post_thumbnail($productId) && !has_post_thumbnail($variationId)) {
                                $img = $product->get_image();
                            } else {
                                $img = $product->get_image(
                                    array(
                                        $settings['productImageMaxWidth'], $settings['productImageMaxHeight']
                                    )
                                );
                            }
                        }

                        $productImg = apply_filters('woocommerce_cart_item_thumbnail', $img, $cart_item, $cart_item_key);

                        if ($product->is_visible()) {
                            $productImg = '<a class="festi-cart-img" href="'.$product->get_permalink().'">'.$productImg.'</a>';
                        } elseif ($product->post->post_parent) {
                            $productImg = '<a class="festi-cart-img" href="'.get_permalink($product->post->post_parent).'">'.$productImg.'</a>';
                        } else {
                            $productImg = '<span class="festi-cart-img">'.$productImg.'</span>';
                        }
                    } ?>
                    <?php
                    $productTitle = '';
                    if (array_key_exists('displayProductTitle', $settings) && !empty($settings['displayProductTitle'])) {
                        if ($product->is_visible()) {
                            $productTitle = apply_filters('woocommerce_cart_item_name', sprintf('<a class="festi-cart-title" href="%s">%s</a>', $product->get_permalink(), $woocommerce->getProductName($product)), $cart_item, $cart_item_key);
                        } elseif ($product->post->post_parent) {
                            $productTitle = apply_filters('woocommerce_cart_item_name', sprintf('<a class="festi-cart-title" href="%s">%s</a>', get_permalink($product->post->post_parent), $woocommerce->getProductName($product)), $cart_item, $cart_item_key);
                        } else {
                            $productTitle = apply_filters('woocommerce_cart_item_name', '<span class="festi-cart-title">'.$woocommerce->getProductName($product).'</span>', $cart_item, $cart_item_key);
                        }

                        $productTitle .= '<br>';

                        if (($cart_item['variation_id'])) {
                            $content = $woocommerce->getCartItemData($cart_item, true);
                            $content = explode("\n", $content);

                            foreach ($content as $value) {
                                if (!$value) {
                                    continue;
                                }
                                $productTitle .= '<span class="festi-cart-product-variation-attribut">'.$value.'</span>';
                            }
                        }
                    }
                    ?>
                    <span id="buy-two" style="font-size:20px; color:red; display:none;"><?php echo "Buy two and save $24.90!"?></span>
                    <tr class="festi-cart-item <?php echo $changeBgColor; ?>">
                        <?php
                        if ($settings['deleteButtonPosition'] == 'left' && array_key_exists('displayDeleteButton', $settings) && !empty($settings['displayDeleteButton'])
                        ) {
                            ?>
                            <td class="festi-cart-product-delete">
                                <a href="<?php echo $cart_item_key; ?>"
                                   class="festi-cart-remove-product" <?php echo $removeAttributes; ?>>
                                   <?php echo apply_filters(WOOCARTPRO_FILTER_POPUP_REMOVE_ITEM_PRODUCT, "Remove", $cart_item); ?>
                                </a>
                            </td>
                            <?php
                        }

                        if (array_key_exists('displayDeleteButton', $settings) && !empty($settings['displayDeleteButton'])) {
                        ?>
                    <td class="festi-cart-product-img">
                    <?php
                    } else {
                    ?>
                        <td colspan="2" class="festi-cart-product-img">
                            <?php
                            }
                            ?>
                            <?php echo $productImg; ?>
                        </td>
                        <td class="festi-cart-product-title">
                            <?php echo $productTitle; ?>

                            <?php if (array_key_exists('displayProductTotalPrice', $settings) && !empty($settings['displayProductTotalPrice'])) {
                                $productPrice = apply_filters('woocommerce_cart_item_price', $woocommerce->getCartProductPrice($product), $cart_item, $cart_item_key);
                                ?>
                                <div class="festi-cart-product-count-and-price">
                                    <?php 
                                    $vars = array(
                                        'settings' => $settings,
                                        'cart_item_key' => $cart_item_key,
                                        'cart_item' => $cart_item,
                                        'productPrice' => $productPrice
                                    );
                                    echo apply_filters(
                                        WOOCARTPRO_FILTER_POPUP_COUNT_ITEM_PRODUCT,
                                        $this->fetch('popup_content_product_title.phtml', $vars),
                                        $vars
                                    ); ?>
                                </div>
                            <?php } ?>
                        </td>
                        <?php
                        if ($settings['deleteButtonPosition'] == 'right' && array_key_exists('displayDeleteButton', $settings) && !empty($settings['displayDeleteButton'])
                        ) {
                            ?>
                            <td class="festi-cart-product-delete">
                                <a href="<?php echo $cart_item_key; ?>"
                                   class="festi-cart-remove-product" <?php echo $removeAttributes; ?>>
                                    <?php echo apply_filters(WOOCARTPRO_FILTER_POPUP_REMOVE_ITEM_PRODUCT, "Remove", $cart_item); ?>
                                </a>
                            </td>
                            <?php
                        }
                        ?>
                    </tr>
                    <?php

                    if ($step == $settings['dropdownListAmountProducts'] && $settings['dropdownListAmountProducts'] != 0) {
                        break;
                    }
                }
            } else {
                ?>
                <tr class="festi-cart-empty">
                    <td class="festi-cart-empty">
                        <?php echo $settings['productListEmptyText']; ?>
                    </td>
                </tr>
                <?php
            }
            ?>


        </table>
    </div>
    <?php if ($settings['displayProductListTotal']) { ?>
        <div class="festi-cart-total subtotal">
            <?php echo $settings['productListTotalText']; ?>
            <?php echo $woocommerce->getCartSubtotal(); ?>
        </div>
    <?php } ?>
    <div id="popup-nav-wrapper">
        <p class="festi-cart-buttons">
            <?php
            if ($settings['productListButtonsQueue'] == 'viewCart') {
                ?>
                <a class="festi-cart-view-cart"
                   href="<?php echo $woocommerce->getCartUrl(); ?>"><?php echo $settings['viewCartButtonText']; ?></a>
                <a class="festi-cart-checkout"
                   href="<?php echo $woocommerce->getCheckoutUrl(); ?>"><?php echo $settings['checkoutButtonText']; ?></a>
                <?php
            } else {
                ?>
                <a class="festi-cart-checkout"
                   href="<?php echo $woocommerce->getCheckoutUrl(); ?>"><?php echo $settings['checkoutButtonText']; ?></a>
                <a class="festi-cart-view-cart"
                   href="<?php echo $woocommerce->getCartUrl(); ?>"><?php echo $settings['viewCartButtonText']; ?></a>
                <?php
            }
            ?>
        </p>
        <?php if ($settings['displayPopupContinueButton']) {?>
            <span class="festi-cart-continue b-close">
                <span class="festi-cart-continue-shopping">
                    <?php echo $settings['popupContinueButtonText']; ?>
                </span>
            </span>
        <?php } ?>
    </div>
    <?php
    if (!empty($settings['popupCrossSellProducts'])) {
        $this->displayCrossSellProducts();
        $userCrossSellTitle = !empty($settings['popupCrossSellTitle']);
        ?>
        <script>
            var isEnableDisplayCrossSellProductsOption = <?php echo $settings['popupCrossSellProducts'] ?>;
            var userCrossSellTitle = <?php echo json_encode($userCrossSellTitle) ?>;
        </script>
        <?php
    }
    ?>
</div>
<?php 
    $skin = '';
    
    if (!empty($settings['quantitySpinnerSkin'])) {
        $skin = $settings['quantitySpinnerSkin'];
    }
    
?>
<script>
    showQuantitySpinnerSkin('<?php echo $skin; ?>');
    
    function showQuantitySpinnerSkin(skin) {
        if (jQuery.ui) {
            var options = {
                icons: { down: "ui-icon-triangle-1-s", up: "ui-icon-triangle-1-n" }
            };
            if (skin == 'skinPlusMinus') {
                options = {
                    icons: { down: "ui-icon-minus", up: "ui-icon-plus" }
                };
            }
            jQuery(".quantitySpinner").spinner(options);  
        }
    }
    
</script>

<script>
    if ( jQuery('.quantitySpinner').attr('aria-valuenow') == 1 ) {
        jQuery("#buy-two").show();
    }
</script>




